eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  # 0으로 설정하면 spring이 임의로 포트를 할당
  port: 0
spring :
  output:
    ansi:
      enabled: always
  application:
    name: product-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordermsa?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: test1234
  jpa:
    database: mysql
    #    InnoDB??
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
